version: '2'

services:
  app:
    image: 10.100.192.200:5000/clickparadise/clickcount:production
    ports:
      - 8080
      - 4848
    labels:
      - "interlock.hostname=prod"
      - "interlock.domain=clickparadise.fr"
      - "interlock.port=8080"
    environment:
      - SERVICE_NAME=clickcount
      - REDIS_HOST=52.58.81.99
  app-blue:
    environment:
      - SERVICE_NAME=clickcount-blue
    extends:
      service: app
  app-green:
    environment:
      - SERVICE_NAME=clickcount-green
    extends:
      service: app
