version: '2'

services:
  interlock:
    image: ehazlett/interlock:1.0
    command: -D run
    ports:
        - 8080
    volumes:
        - ./config.toml:/bin/config.toml
        - nginx:/etc/conf
        # - haproxy:/etc
  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/conf/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock
    volumes:
        - nginx:/etc/conf
  # haproxy:
  #   image: haproxy:latest
  #   ports:
  #       - 80:80
  #   labels:
  #       - "interlock.ext.name=haproxy"
  #   links:
  #       - interlock:interlock
  #   volumes:
  #       - haproxy:/usr/local/etc/haproxy
volumes:
  nginx: {}
  # haproxy: {}
