---
# docker-engine is the default package name
docker_pkg_name: docker-engine
docker_apt_cache_valid_time: 600

# Place to get apt repository key
apt_key_url: https://apt.dockerproject.org/gpg
# apt repository key signature
apt_key_sig: 2C52609D
# Name of the apt repository for docker
apt_repository: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main
# The following help expose a docker port or to add additional options when
# running docker daemon.  The default is to not use any special options.
docker_opts: >
  --insecure-registry 10.100.192.200:5000
docker_extra_opts: >
  -H tcp://0.0.0.0:2375
  -H unix:///var/run/docker.sock
  --cluster-store=consul://{{ consul_server_ip }}:8500/swarm
  --cluster-advertise=eth1:2375
# List of users to be added to 'docker' system group
docker_group_members: [vagrant]
# Versions for the python packages that are installed installed
pip_version_pip: 8.1.1
pip_version_setuptools: 20.3.1
pip_version_docker_py: 1.2.3
pip_version_docker_compose: 1.6.2

# Set to 'yes' or 'true' to enable updates (sets 'latest' in apt module)
update_docker_package: no

# If this variable is set to true kernel updates and host restarts are permitted.
# Warning: Use with caution in production environments.
kernel_update_and_reboot_permitted: yes

kernel_pkg_state: latest
