- hosts: prod-master
  remote_user: vagrant
  serial: 1
  sudo: yes
  roles:
    - java
    - jenkins-node
    - docker
    - consul
    - swarm
    - registrator

- hosts: prod-node
  remote_user: vagrant
  serial: 1
  sudo: yes
  roles:
    - docker
    - swarm
    - consul
    - registrator
